apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: oxeo-eks
  region: eu-central-1
  version: '1.22'
  tags:
    karpenter.sh/discovery: oxeo-eks
iam:
  withOIDC: true # required

karpenter:
  version: '0.9.1'

managedNodeGroups:
  - name: ng-small
    instanceType: m5.large
    minSize: 1
    maxSize: 10
    desiredCapacity: 1
