apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  externalName: lk-dev.cstqmhnp1nqd.eu-central-1.rds.amazonaws.com
  selector:
    app: postgres
  type: ExternalName
status:
  loadBalancer: {}
