kind: Pod
metadata:
  labels:
    foo: bar
spec:
  restartPolicy: Never
  containers:
  - image: daskdev/dask:latest
  - image: "eu.gcr.io/oxeo-main/oxeo-flows:latest"
    imagePullPolicy: IfNotPresent
    args: [dask-worker, --nthreads, '1', --no-dashboard, --memory-limit, 2GB, --death-timeout, '60']
    name: dask
    env:
      - name: EXTRA_PIP_PACKAGES
        value: distributed==2021.11.2
    resources:
      limits:
        cpu: 1
        memory: 2G
      requests:
        cpu: 1
        memory: 2G
