name: build-images

on:
  workflow_dispatch:

jobs:
  cloudbuild-gpu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: oxeo-main
          service_account_key: ${{ secrets.GCP_PREFECT_SERV_ACC }}
          export_default_credentials: true

      - name: Submit to Cloud Build
        run: |
          gcloud builds submit . --config=infra/cloudbuild-flows.yaml
