name: build-images

on:
  push:
    branches: [ main ]
    paths:
      - 'setup.cfg'
      - 'infra/Dockerfile.oxeo-flows'
      - 'infra/packer/packer.json'
      - 'infra/cloudbuild-oxeo-flows.yaml'
      - 'oxeo/flows/utils.py'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cloudbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: oxeo-main
          service_account_key: ${{ secrets.GCP_PREFECT_SERV_ACC }}
          export_default_credentials: true

      - name: Submit to Cloud Build
        run: |
          gcloud builds submit . --config=infra/cloudbuild-oxeo-flows.yaml

  packer:
    needs: cloudbuild
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build VM image with Packer
        uses: oxfordeo/packer-action@master
        with:
          only: googlecompute
          secret: ${{ secrets.GCP_PREFECT_SERV_ACC }}
          template: infra/packer/packer.json
          options: "-force"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: '/tmp/packer-secret'
