name: prefect-register

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: register flows
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
        run: |
          pip install -r requirements.txt
          prefect backend cloud
          prefect auth login --key="$PREFECT_API_KEY"
          prefect register --project=testing -p oxeo/flows/
