name: prefect-register

on:
  push:
    branches: [ main ]
    paths:
      - 'oxeo/flows/*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.10

      - name: Install GDAL dependencies
        run: |
          sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install gdal-bin libgdal-dev
          pip install wheel

      - name: Install dependencies
        run: pip install .

      - name: Register with Prefect
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
        run: |
          prefect backend cloud
          prefect auth login --key="$PREFECT_API_KEY"
          prefect register --project=water -p oxeo/flows/
